### ISSUE TITLE
version 0.4.4 - after cb_set_data, x,y view range is not auto set. whereas it works perfectly in 0.3.3

### ISSUE THREAD

**Issue by vvdigitaal** [domarm-comat/pglive#8] opened 2022-10-02 12:55 UTC
Dear Sir,
 I have been using pglive 0.3.3 and very much impressed with your work. Thank you very much for developing the module, it really simplifies  the development effort to making pyqtgraph live. I use pglive for plotting live stock quote (just a live line plot, i have also tested candleplot too).

problem : I have recently updated the version to 0.4.4 and my previously working code is not usable now. I use livelineplot, and cb_set_data and cb_append_data_point to load initial data and append live data respectively. In the ver0.3.3, when the initial set of historical data is loaded using cb_set_data, the x,y axis view is is properly set and can see the plot (even if live data is unavailable). Whereas in the ver0.4.4, possibly because of introducing the x and y live axis controller, once initial data is set using cb_set_data , the plot view is blank. Note,I use datetime axis on X. Once cb_set_data command is issued, the x axis defaults to epoch (1970) and y axis is 0 to1. I am unable to autorange even by clicking the 'A' button of pyqtgraph which is on the bottom left.

  However, once the live data arrives, the plot shows up in the view box. Please let me know the method to enable x,y auto range during normal conditions (i.e, prior to the arrival of live data). I need to view historical data sometimes, when the live tick is not available. Actually, I would like to know the autorange command just like we use for pg.PlotWidget so that i can enable it as and when the view changes. I do not want to use pg.PlotWidget commands like setXrange, setLimits etc beacuse it interferes with pglive auto range features during live tick plotting.

**Comment by domarm-comat** [comment] 2022-10-02 19:05
Dear VV,

thanks a lot for your interest in pglive, I'm very happy, that you find it useful.

I looked into you issue and I hope I found solution for your problem. When I introduced LiveAxisRange feature, I forgot to apply sig_data_roll_tick for cb_set_data. Therefore View was not properly updated, when cb_set_data was called, but it was working for cb_append_data_point. I made a quick fix and released version 0.4.5. Please try it, and see if that fix your problem.

If not, let me now, and please attach small code example, which I can use to reproduce your issue.

Thanks for reporting this issue. People who uses pglive have already suggested new interesting features and improvements. Please, don't hesitate to suggest new types of plots or new features, that would help you in your projects.

**Comment by vvdigitaal** [comment] 2022-10-03 00:39
Dear Domarm,
  Very much appreciate your prompt reply and instant release of a version after fixing. I will try and let you know.
 I have several questions to ask, few issues to report and features to suggest too, but I would like to take up one at a time. To begin with, i request you to share the syntax / method to set auto Y range after a Zoom/PAN. Reason I need to know this is because, when I zoom out /in, I need to set Y range of axis to maximize the candle size within the view area. Currently, in the liveplotwidget, just after one-time mouse wheel scroll / click-move, the auto scrolling (and auto range) of live plot stops completely not just in candlestick plot but the livelineplot too. I keep pressing the 'A' button (left bottom) to reset the view and sometimes it starts the live scroll and some other time it doesn't work too (refer to below screenshot). 

below image shows the candles that are compressed in height. the Qrectf of bounding rectangle of all the candles in the array, but it must give the bounds of what is visible in the view. I have modified the method in my sub-class , but it interferes with live plot I guess, not sure. But my code for bounding rectangle works beautifully in a static pyqtgraph plot (pg.Plotwidget)

![image](https://user-images.githubusercontent.com/96345999/193482815-0b37d444-28b1-4f2e-93f6-1831b8ef5feb.png)

    def boundingRect(self) -> QtCore.QRect:
            viewRect = self.thisPlotWidget.viewRect()
            xmin = int(viewRect.left())
            xmax = int( xmin + viewRect.width())
            xd = np.asarray(list(self.x_data))
            try :
                xleftIndx = ( np.abs(xd-xmin) ).argmin()
                xRightIndx =( np.abs(xd-xmax) ).argmin()
                # logging.info(f"{xleftIndx}, {xRightIndx}, len {len(xd)}, type {type(xRightIndx)}")

            except :
                    pass
            try :
                if xleftIndx is not None and xRightIndx is not None :
                    yd = pd.DataFrame(list(self.y_data))
                    ymax = yd.loc[xleftIndx:xRightIndx,1].max()
                    ymin = yd.loc[xleftIndx:xRightIndx,2].min()

                    brect = QRectF(xd[xleftIndx],ymin,(xd[xRightIndx]-xd[xleftIndx]),(ymax-ymin))
                    # logging.info(f"Num Candles: {xRightIndx-xleftIndx}, xmin : {pd.Timestamp(xmin,unit='s')}, xmax : {pd.Timestamp(xmax,unit='s')}, ymin : {ymin} : ymax : {ymax}")
            except:
                    brect = QtCore.QRectF(self.picture.boundingRect())
            
            # logging.info(f"brect now {brect}")

            return brect



more details , which is not very important :

Moreover, the ignorebounds (which is a pg.PlotWidget attribute) is not allowed in liveplotwidget and I do several work around solutions such using pyqtgraph.PlotWidget and the dataconnector instead of pglive's liveplotwidget and continued to use ignorebounds in a different way. By doing this, i am forced to use my own cross hair class.

**Comment by vvdigitaal** [comment] 2022-10-03 00:54
forgot to mention, in the above code calculating ymax, ymin, I use col1,col2 of dataframe (created from the Ydata tuple) which has High and Low values of candle, ie, OHLC convention. Whereas your original candlestick class  (and candle generator)  uses open close low high convention. Just wanted to clarify this point so that you may not get confused.

ymax = yd.loc[xleftIndx:xRightIndx,1].max(), 
ymin = yd.loc[xleftIndx:xRightIndx,2].min(),

**Comment by domarm-comat** [comment] 2022-10-03 17:34
Ok, so it's a bit harder for me now to understand what you would like to achieve. I will try to answer as best as I can.

- First, when you pan or zoom, Autorange is imminently stopped and you must click "A" to enable it again. This is not a bug, but default pyqtgraph behavior. Otherwise you wont be able to move view, since it will be always changed when new value appear.
- I wouldn't change boundingRect(), since it will interfere with LiveRange handling. If you want to alter X, Y auto-range behavior, you can override [get_y_range](https://github.com/domarm-comat/pglive/blob/00b0a44048d553b12490808e9784339057d3c60b/pglive/sources/live_axis_range.py#L48) of [live_axis_range.py](https://github.com/domarm-comat/pglive/blob/00b0a44048d553b12490808e9784339057d3c60b/pglive/sources/live_axis_range.py).
There you can return (Ymin, Ymax) as you desire.
Same for [get_x_range](https://github.com/domarm-comat/pglive/blob/00b0a44048d553b12490808e9784339057d3c60b/pglive/sources/live_axis_range.py#L24), returning (Xmin, Xmax). Like that you can easily control Bounds and what is displayed in a view.
You can even disable LiveAxis altogether by subclassing [LivePlotWidget](https://github.com/domarm-comat/pglive/blob/00b0a44048d553b12490808e9784339057d3c60b/pglive/sources/live_plot_widget.py) and removing these three lines:
```
self.disableAutoRange()
self.getPlotItem().vb.setRange = self.set_range
self.getPlotItem().vb.sigRangeChangedManually.connect(self.sm)
```
Of course, like that LiveAxis and all related features won't work, but you can use all the default Autorange and Bound features of pyqtgraph.
- Ignorebounds is not working as you are saying. I will try to address it in future releases.
- Maybe feature like making X axis free to scroll, but fix Y to min, max what is currently in the view might be something interesting for candlestick plot.

Anyhow, this question was related to view_range not auto set on cb_data_set callback. Let me know if that was fixed and we can close this issue. If I didn't answer your following question properly, just open up new issue, so it's easier for others (and us) to follow as well. Don't worry to open more issues if needed, it's better than solving multiple things in one issue.

**Comment by vvdigitaal** [comment] 2022-10-04 08:46
Dear Domarm,
   Thank you very much for the detailed reply. Yes, your response very well answered my doubts and I will try out the suggestions soon. if needed, I will open up a new issue for this as well as for every different issue. 

Regarding the cb_set_data, yes , the new version 0.4.5 updates the view box for both cb_set_data as well as append data, i.e, the plot is displayed properly with XY max/min. But, there is some new issue shows up in the release, I am yet to explore it in detail and will send you a sample program to recreate the problem from your side. Basically, the autorange XY fails when issuing cb_set_data for the 2nd or 3rd time, that is when selecting the different Stock symbol and set its initial OHLC data (same behavior even with the livelineplot of just Close price 1D series). The plot shows up as a tiny dot on one of the four corners of the view box and I keep zooming in as much to bring it to the view.  I wish to provide you the exact steps to recreate the problem, please bear with me till then.

**Comment by domarm-comat** [comment] 2022-10-04 11:24
Great. Example of showing what is wrong is the best for finding and solving the issue. It would be highly appreciated. Since it seems this is mostly isolated to candlestick plot and setting data in DataConnector, I've created new branch [candlestick_bug_fixes](https://github.com/domarm-comat/pglive/tree/candlestick_bug_fixes), please use that branch for future reference. Once we squash all the bugs, I will merge it into main branch and make a release.

I've already made some additional small changes, that might or might not fix your issue after calling cb_set_data, give it a shot. I will wait for full example as you said.

**Comment by vvdigitaal** [comment] 2022-10-10 04:10
Sure, I will provide several feedback which I have in mind, along with sample codes. I may need a week to respond to you.

**Comment by vvdigitaal** [comment] 2022-10-23 13:26
i will revert in a while, am sorry about the delay. I need to work on the candlestick chart thoroughly to give you a concise report.

**Comment by domarm-comat** [comment] 2022-11-28 15:53
I did few updates regarding LiveAxis and LiveAxisRange. There were some bugs fixed as well. Is the problem still occurring for you in version 0.5.5?

**Closed as completed** 2022-12-16 06:00 UTC
