### ISSUE TITLE
Understanding DataConnector update_rate and data append time

### ISSUE THREAD

**Issue by slartz42** [domarm-comat/pglive#28] opened 2023-08-22 12:56 UTC
Hello,

I am currently working on a project that requires sampling packets of data at a high speed. For this example, I am sampling 8 channels of sensor data at 20kHz with a packet time of 6.4ms, downsampling the data to a small numpy array, and appending each channel using cb_append_data_array with list comprehension as shown below. The actual data I'm appending to each connector is a 1-D array with no more than 10 samples.

`[connector.cb_append_data_array(np.ma.compressed(units[:, index]), np.ma.compressed(x_time[:, index])) for index, connector in enumerate(data_connectors)]  `

Right now I'm trying to reduce the CPU usage of my program, which is currently in the range of 40-50% when running a plot_rate of 15 Hz. With the code above commented out (not plotting any data), my CPU usage is <5% so pyqtgraph is using the majority of the CPU consumption.

I'm struggling to understand the effect of changing the DataConnector update_rate, I have found that if the value is set too low, some of the data is "dropped" and does not get plotted. If I set the value too high, does this negatively impact CPU usage? Where should this value be set?

Also, I have found the connector appending speed varies significantly, is this directly related to the update_rate setting?

![image](https://github.com/domarm-comat/pglive/assets/52103361/f1170695-0613-4f8b-bbd9-fec006c5f7db)

**Comment by domarm-comat** [comment] 2023-08-22 13:40
Hey!

Ok, as far as I understood from your situation, you want to plot all of your data, but also keep CPU usage low.
You sample rate is high, so some optimizations are necessarry.

`update_rate` only accept - append - data which is coming at lower rate than `update_rate`. So yes, using this approach will remove certain portion of your input data. It's not suitable if you want to plot everything.

There is another `DataConnector` argument called `plot_rate`, which accept all the data at any rate, but only refreshes the plot at given plot_rate in Hz. Plot repaint is the most CPU demanding task.

So, leave `update_rate` empty and just set `plot_rate` to something like `5` - 5Hz plot update (play around with value which suits your application). This should lower your CPU usage greatly and plotting everything. Of course you can combine both reats if you want.

Please have a look at the example: [plot_reate.py](https://github.com/domarm-comat/pglive/blob/main/pglive/examples_pyqt6/plot_rate.py). There are also other ways to optimize plotting without sacrificing the speed. Like [live_plot_range.py](https://github.com/domarm-comat/pglive/blob/main/pglive/examples_pyqt6/live_plot_range.py). It depends on what is important for you to show and how often.

As for append times. That is really situational. As everything runs in one process, it all depends on the current process occupation. that said, final time pretty much depends on how much is your process under the load and you can definetly see jumps in time.

Good luck and thanks for using pglive!

**Comment by slartz42** [comment] 2023-08-22 16:52
Thanks for the advice, reducing the plot_rate did reduce the CPU, I also left update_rate empty which I didn't realize you could do.

I'll try out the live_plot_range as well and see if I can make further improvements

**Comment by slartz42** [comment] 2023-08-23 11:40
Ok so the live_plot_range definitely helped, my CPU usage is down to 15-20% at 25 FPS! I'm still trying to understand how to properly implement roll_on_tick, is a "tick" an update of the plot, or an appending of the data connector? I'm trying to set the window to roll every 30 seconds, but it doesn't seem to do what I expect.

Also, is there a way to synchronize the x axis on multiple plots? Right now one plot is slightly offset for some reason: 

![image](https://github.com/domarm-comat/pglive/assets/52103361/f4e716b8-3b00-433f-b31a-fcc60ddd0374)

**Comment by domarm-comat** [comment] 2023-08-23 13:23
Yes, one tick equals one point append. So if you append 60 points at rate 1Hz, roll_on_tick=60 should roll plot at 1 minute rate.
If you use `cb_append_data_array`, it's not only one tick, but length of the appended array. So if you append array of size 60, it will mean `ticks` + 60. But there might be some overlooked bugs with `cb_append_data_array` as it was added very recently and was not very much tested so far. So if you are sure plot is not behaving as it should, give me some reproducible example and I can have a look at it.

As for syncing, are you talking about replotting synchronization, or how it looks? Looking into your image, Power plot is not aligned with other plots. That's because how pyqtgraph is rendering tick strings. You don't have any decimal points in the Power plot while there are in others (Y axis). That is causing X axis not being aligned properly.
Easiest fix you can try is to set tick spacing: [Reference in manual](https://pyqtgraph.readthedocs.io/en/latest/api_reference/graphicsItems/axisitem.html#pyqtgraph.AxisItem.setTickSpacing)

For example, having major ticks separated by 1 and minor ticks by 0.5. That way you should have decimal points in each Y axis and that should make X axis looks aligned.
`left_axis.setTickSpacing(1, 0.5)`

**Comment by slartz42** [comment] 2023-08-24 13:42
Ok, if I tested this correctly, roll_on_tick does not seem to be working as you say, but it's also possible my math is wrong. Here are my settings:

Maximum number of connector points: 1,000
Sample rate: 200 Hz
Connector time width: 1,000 points / 200 Hz = 5 seconds

I want the window to "roll" when the connector reaches its max width of 5 seconds:
roll_on_tick = 200 ticks per second * 5 second = 1,000

When the graph starts, I get a window width of 3.2 seconds when I expected it to be 5 seconds:

![image](https://github.com/domarm-comat/pglive/assets/52103361/28214142-b274-420f-a12e-d7f4110c8d03)

When the window finally rolls, its not until 60 seconds:

![image](https://github.com/domarm-comat/pglive/assets/52103361/c93420f1-847e-4959-8f8b-d2560668263c)

It almost seems like ticks are getting "dropped" and not counted properly when using cb_append_data_array

**Comment by domarm-comat** [comment] 2023-08-25 10:19
Ok, I will do some testing with what you're feeding to the plots and get back to you. Thanks for your patience :).

**Comment by domarm-comat** [comment] 2023-08-27 16:38
Ok, I believe the problem was when plot was trying to generate x range using _array callback. I added new method which should return correct size of 1 tick. Could you please try code from branch ([live_axis_range_bugfix](https://github.com/domarm-comat/pglive/tree/live_axis_range_bugfix)). If it fixes your problem I will merge it into main branch.

**Comment by slartz42** [comment] 2023-08-29 22:39
Sorry for the delay, it looks like that worked, thanks!

**Comment by domarm-comat** [comment] 2023-08-30 06:56
Great, I merged the branch into main. All updates should be now be in effect in version 0.6.9.

**Closed as completed by domarm-comat** 2023-08-30 06:56 UTC
