### ISSUE TITLE
Formatting x axis timestamp for Axis.TIME

### ISSUE THREAD

**Issue by optio50** [domarm-comat/pglive#34] opened 2023-11-22 06:55 UTC
Hello,
After much trial and error I think I have found the problem with what I thought was a roll_on_tick issue (it was only a symptom of the timestamp issue).
It would seem that its related to my Axis.TIME time format.
prior to 0.6.9 I have formatted and used the timestamp as follows.

(relevant portions)

import time
MP_bottom_axis = LiveAxis("bottom", **{Axis.TICK_FORMAT: Axis.TIME})
timestamp = time.time()
self.Exterior_Temp_connector.cb_append_data_point(TempSensor3, timestamp)

This no longer works and it results in a chart that is zoomed out.
omitting the timestamp in the connector.cb_append_data_point, it displays fine but obviously the time is incorrect.

In all the examples you have provided, such as (live_plot_range.py) the time stamp always starts at 14:00

Can you provide an example to show how to update connector.cb_append_data_point with the time of the data update?

I can provide a more complete example if needed.

**Comment by domarm-comat** [comment] 2023-11-23 17:43
Ok, I found out where the problem is. The problem appears, when using LiveAxisRange and roll_on_tick and values much larger than 0 (as time.time() is). I will think about ho to fix it using some smart general solution which won't brake other things :). Thanks for your patience. I will try to fix soon.

**Comment by domarm-comat** [comment] 2023-11-23 20:03
@optio50, I made a possible fix for your issue. Could you please try to run your code against [https://github.com/domarm-comat/pglive/tree/liveplot_range_fix](https://github.com/domarm-comat/pglive/tree/liveplot_range_fix) branch?
Let me know if that helps. If not, please provide me with some sample data I can use for debugging.

**Comment by optio50** [comment] 2023-11-23 23:43
I haven't tried it for very long but it seems to be working well. :-)

As always, thank you for your prompt attention and hard work.

**Comment by domarm-comat** [comment] 2023-11-24 06:46
You're welcome. Thanks for your continous interest and bughunt :). I merged all changes in v0.7.3 If anything, just open new issue.

**Closed as completed by domarm-comat** 2023-11-24 06:46 UTC
